version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - keycloak
      - redis
      - fastapi
      # - webapp
  # webapp:
  #   build: ./webapp
  fastapi:
    build: ./fastapi
  keycloak:
    build: ./keycloak
    ports:
      - 8080:8080
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
  redis:
    image: "redis:alpine"